[package]
name = "ocl"
version = "0.7.2"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "OpenCL bindings and interfaces for Rust."
documentation = "http://doc.cogciprocate.com/ocl/index.html"
homepage = "https://github.com/cogciprocate/ocl_rust"
repository = "https://github.com/cogciprocate/ocl_rust"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT"
exclude = ["target/*", "*.png"]

# [dependencies.bitflags]
# git = "https://github.com/rust-lang-nursery/bitflags.git"

[dependencies]
# find_folder = "*"
rand = "0.3"
num = "0.1"
libc = "0.2"
enum_primitive = "0.1"
bitflags = "0.5"

[dev-dependencies]
# time = "*"
image = "0.7"

[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false
# Set false to make sure we're not relying overly on any debug assertions.
debug-assertions = false
codegen-units = 1

