[package]
name = "ocl"
version = "0.2.0"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "OpenCL interfaces for Rust."
documentation = "https://github.com/cogciprocate/ocl_rust"
homepage = "https://github.com/cogciprocate/ocl_rust"
repository = "https://github.com/cogciprocate/ocl_rust"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT"
exclude = ["target/*"]

[dependencies]
rand = "0.3"
num = "0.1"
libc = "0.2"
enum_primitive = "0.1"
