[package]
name = "ocl"
version = "0.0.1"
authors = ["Nick Sanders <github.com/c0gent>"]
description = "OpenCL interfaces for Rust."
documentation = "https://github.com/cogciprocate/ocl_rust"
homepage = "https://github.com/cogciprocate/ocl_rust"
repository = "https://github.com/cogciprocate/ocl_rust"
readme = "README.md"
keywords = ["opencl", "ocl", "envoy", "gpu", "gpgpu", "amd", "nvidia"]
license = "GPL-2.0"
exclude = ["target/*"]

[dependencies]
#bitflags = "0.1.1"
rand = "0.3.5"
num = "0.1.19"
libc = "0.1.5"
enum_primitive = "0.0.2"
